# Setup

## Stock Imports

### IDE Stuff

#### Installing New Packages

In [2]:
# Jupyter Plugins that make things much nicer:
# * Collapsible_Headings
# * hide_code
# * jupyterlab-code-cell-collapser
# * jupyterlab_templates

Depending on how many installations of Python you have on your system, doing a simple `conda install` or `pip install` will put the module in the wrong installation.  This makes sure it lands in the installation corresponding to the current notebook.

In [3]:
# Code for installing packages
# !conda install --yes --prefix {sys.prefix} shapely
# !{sys.executable} -m pip install shapely

#### Notebook Customization

This will change the fonts in Anaconda JupyterLab and Notebook.  I find the rendered mardown heading fonts (H1, H2, H3, etc) to be too similar.  This will alternate between italicized and normal fonts for headings.  Additionally, it adds a small indent that grows with heading level.  H1 is centered.

In [4]:
import IPython
css_str = """
<link rel="preconnect" href="https://fonts.gstatic.com">

<link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@300;400;600&family=Playfair+Display+SC&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora">
<link href="https://fonts.googleapis.com/css2?family=IM+Fell+Double+Pica:ital@1&display=swap" rel="stylesheet">
    <style>
h1 { color: #7c795d; font-family: 'Playfair Display SC', serif; text-indent: 00px; text-align: center;}
h2 { color: #7c795d; font-family: 'Lora', serif;                text-indent: 00px; text-align: left; }
h3 { color: #7c795d; font-family: 'IM Fell Double Pica', serif; text-indent: 15px; text-align: left; }
h4 { color: #7c795d; font-family: 'Lora', Arial, serif;         text-indent: 30px; text-align: left}
h5 { color: #71a832; font-family: 'IM Fell Double Pica', serif; text-indent: 45px; text-align: left}

"""
IPython.display.HTML(css_str)

Allows for changes in packages to be detected and immediately incorporated into the present notebook without resetting the kernel.

In [5]:
%load_ext autoreload
%autoreload 2

By default, Jupyter returns the last expression (and won't return this if it is a statement).  Sometimes we want different behavior that is more similar to Mathematica

In [6]:
from IPython.core.interactiveshell import InteractiveShell

# pretty print only the last output of the cell
InteractiveShell.ast_node_interactivity = 'last_expr' # ['all', 'last', 'last_expr', 'none', 'last_expr_or_assign']

In [7]:
x = 2
y = 3

In [8]:
x = 2

In [9]:
del x, y

### Python Libraries

Standard Python imports

In [10]:
import os, sys, time, glob

It is a good idea to record the starting working directory before it gets changed around.  Note that this can be problematic depending on how you open the notebook, but it works most of the time.

In [11]:
baseDir = os.getcwd()
baseDir

'c:\\Users\\brianedw\\Desktop\\Jupyter Template'

It is also nice to know if what is running is a notebook, or a python script generated from the notebook.

In [12]:
mainQ = (__name__ == '__main__')
if mainQ:
    print("This is the main file")

This is the main file


JupyterLab doesn't support navigation to other drives.  This is a handy trick to make folders in other drives "appear" as if they're local.  It even works on network shares.  

PowerShell Command to Map network drives:
```powershell
New-Item -ItemType SymbolicLink -Path "c:\users\brianedw\group_share" -Target "\\158.130.53.35\_Group Share"
```


### Notebook Interactivity

Adds a nice progress bar for visualizing a loop iterator.  See snippets.

In [13]:
from tqdm import tqdm

Useful for monitoring a calculation's progress.

In [14]:
from IPython.display import clear_output

In [15]:
for i in range(5):
    print(i)
    time.sleep(0.1)
    clear_output(wait=True)
del(i)

4


A nice sound to play when long calculations are completed.

In [16]:
import winsound

def soundDone():
    soundfile = "C:/Windows/Media/ring01.wav"
    winsound.PlaySound(soundfile, winsound.SND_FILENAME | winsound.SND_ASYNC)

### Functional Programming

It is very common in data analysis to run data through a series of transformations, often called a "pipe".  The advantage of this is the arguments are contained with the functions and it is more readable (once you get used to it!).  For instance, in `Mathematica`, 

`H(#, 4)& @ G(#,3)& @ F(#,2)& @ 1  =>  H(G(F(1,2),3),4).`

In the former, it is clear that `3` belongs to `G`.  In the latter, you need to count parenthesis.  This typically makes use of "lambda functions" or "pure functions".  As a primarily Object Oriented Programming (OOP) language, Python doesn't natively support much of this Functional paradigm.  However, it does treat functions as objects which can be manipulated.  Given the utility of Functional Programming, there are several packages that attempt to bring it into the language, each with varying success.

In [17]:
# from pipetools import where, X, pipe
# 10 > (pipe | range | where(X % 2) | sum)

In [18]:
# from pipey import Pipeable

# Print = Pipeable(print)
# @Pipeable
# def add(a,b): return a + b
# @Pipeable
# def sqr(b): return b*b

# np.array([3, 4]) >> sqr >> add(1000)

The `toolz` library has a lot of great functions for performing common operations on iterables, functions, and dictionaries.

In [19]:
# from toolz.itertoolz import ()
from toolz.functoolz import (curry, pipe, thread_first)
# from toolz.dicttoolz import ()

In [20]:
@curry
def add(x, y): return x + y
@curry
def pow(x, y): return x**y
thread_first(1, add(y=4), pow(y=2))  # pow(add(1, 4), 2)

25

In [21]:
from mini_lambda import InputVar, as_function
_ = as_function
X = InputVar('X')

In [22]:
_(X+3)(10)

13

In [23]:
thread_first(1, add(y=4), _(pow(x=2, y=X)))  # pow(2, add(1, 4))

32

In [24]:
thread_first(1, _(X+4), _(2**X))  # pow(add(1, 4), 2)

32

In [25]:
del(add, pow, X, _)

### Scientific Programming

In [26]:
from math import sin, cos, radians, degrees, tan, sinh, cosh, tanh, exp, pi, tau

In [27]:
deg = radians(1)    # so that we can refer to 90*deg
I = 1j              # potentially neater imaginary nomenclature.

In [129]:
import numpy as np  # Does high performance dense array operations
np.set_printoptions(edgeitems=30, linewidth=100000,
                    formatter=dict(float=lambda x: "%.3g" % x))
import scipy as sp
import pandas as pd
import PIL 

In [29]:
import skimage

In [30]:
# Python function compilization.  Makes things very fast.  Function must only include Numpy and basic Python.  No custom classes.
import numba
from numba import njit

In [31]:
import sympy as sp
# sp.init_printing(pretty_print=True)
# sp.init_printing(pretty_print=False)

In [32]:
import pint

### Plotting

In [33]:
import bokeh
from bokeh.io import output_notebook
from bokeh.plotting import figure, show
output_notebook()
bokeh.io.curdoc().theme = 'dark_minimal'

Loading BokehJS ...

## Custom Imports

In [34]:
from UtilityMath import (plotComplexArray, 
                         RandomComplexCircularMatrix, RandomComplexGaussianMatrix,
                         PolarPlot,
                         RescaleToUnitary,
                         ReIm,
                         MatrixSqError, MatrixError, MatrixErrorNormalized)
from Logger import Logger

## Code Snippets

### Cell Updating

In [35]:
if mainQ and False:
    for f in range(10):
        clear_output(wait=True)
        print(f)
        time.sleep(0.5)

In [36]:
if mainQ and False:
    for i in tqdm(range(100000000)):
        pass

### Bokeh Simple Line Plot

In [37]:
ts = np.linspace(0, 4, num=300)

In [38]:
xs = 5.0 * ts

In [39]:
ys = -9.8*ts**2 + 50*ts + 0

In [40]:
fig = figure(x_range=(min(xs), max(xs)), y_range=(min(ys), max(ys)), 
             plot_width=800, plot_height=400,
             title='Trajectory')
fig.xaxis.axis_label = "x (m)"
fig.yaxis.axis_label = "y (m)"
fig.line(x=xs, y=ys)
if mainQ: show(fig)

In [41]:
del ts, xs, ys, fig

NameError: name 'x' is not defined

### Units with Pint

In [42]:
from pint import UnitRegistry
ureg = UnitRegistry()

In [43]:
d1 = 140.*ureg('thou')
d2 = 0.891*ureg('mm')
dTot = d1 + d2
dTot.to('um')

4447.0 <Unit('micrometer')>

In [44]:
del(d1, d2, dTot)

### Error Propagation with `pint`

In [45]:
R1 = (130*ureg('ohm')).plus_minus(0.05, relative=True)
print(R1)
R2 = (150*ureg('ohm')).plus_minus(0.05, relative=True)
print(R2)
VIn = (10*ureg('V')).plus_minus(0.005)
print(VIn*R1/(R1+R2))

(130 +/- 6) ohm
(150 +/- 8) ohm
(4.64 +/- 0.18) volt


In [46]:
del(R1, R2, VIn)

### Statistical Error Propagation with `uncertainties`

In [47]:
from uncertainties import ufloat

In [48]:
x1 = ufloat(1, 0.1)
x2 = ufloat(1, 0.1)
print(x1, x2, x1 + x2)

1.00+/-0.10 1.00+/-0.10 2.00+/-0.14


### Interval Error Propagation with `mpMath`

In [65]:
from mpmath import iv

In [66]:
x = iv.mpf(['-0.1', '0.1'])
print(x)


[-0.10000000000000000555, 0.10000000000000000555]


In [67]:
print(iv.sin(x))
print(iv.cos(x))

[-0.099833416646828168628, 0.099833416646828168628]
[0.99500416527802570954, 1.0]


In [68]:
del x

# Work

## Clements Decomposition

In [418]:
from numpy import cos, sin, exp

In [419]:
np.set_printoptions(edgeitems=30, linewidth=100000,
                    formatter=dict(float=lambda x: "%.2g" % x))

### Unitary Matrix Generation

In [383]:
def isPassive(M, verbose=False):
    Im = np.identity(M.shape[0])
    TH = np.conj(M.T)
    eigVals = np.linalg.eigvals(Im - TH @ M).real
    if verbose:
        print(eigVals)
    isPassive = np.alltrue(eigVals >= -1e-12)
    return isPassive

In [384]:
testM = np.identity(5, dtype='complex')
isPassive(testM)

True

In [391]:
def getRandomUnitaryMatrix(n=5, verbose=False):
    rMat = RandomComplexCircularMatrix(1, (n, n))
    # print(rMat)
    U, Svec, Vh = np.linalg.svd(rMat, full_matrices=True)
    S = np.diag(Svec)
    recovery = U @ S @ Vh
    if verbose:
        print("Successful SVD Decomposition:", np.allclose(recovery, rMat))
    M = U @ Vh
    return M

In [392]:
U = getRandomUnitaryMatrix(n=5)

### Mixer

In [497]:
class Mixer:
    pass

In [498]:
def __init__(self, theta_phi, lines):
    self.theta = theta_phi[0]
    self.phi = theta_phi[1]
    self.lines = lines
    
setattr(Mixer, "__init__", __init__)

In [499]:
def M(self):
    a = [[ exp(I*self.phi) * cos(self.theta), -sin(self.theta)], 
         [ exp(I*self.phi) * sin(self.theta),  cos(self.theta)]]
    return np.array(a)

setattr(Mixer, "M", M)

In [500]:
def Minv(self):
    a = [[ exp(-I*self.phi) * cos(self.theta),  exp(-I*self.phi) * sin(self.theta)], 
         [                   -sin(self.theta),                     cos(self.theta)]]
    return np.array(a)

setattr(Mixer, "Minv", Minv)

In [501]:
def T(self, N, lines):
    T = np.identity(N, dtype='complex')
    a = self.M()
    m,n = lines
    T[m, m] = a[0,0]
    T[m, n] = a[0,1]
    T[n, m] = a[1,0]
    T[n, n] = a[1,1]
    return T

setattr(Mixer, "T", T)

In [505]:
def Tinv(self, N, lines):
    T = np.identity(N, dtype='complex')
    a = self.Minv()
    m,n = lines
    T[m, m] = a[0,0]
    T[m, n] = a[0,1]
    T[n, m] = a[1,0]
    T[n, n] = a[1,1]
    return T

setattr(Mixer, "Tinv", Tinv)

In [506]:
mixer = Mixer(theta_phi=(0.2*pi, 0.3*pi), lines=(0, 1))

In [507]:
mixer.T(N=2, lines=(0,1))

array([[ 0.47552826+0.6545085j , -0.58778525+0.j        ],
       [ 0.3454915 +0.47552826j,  0.80901699+0.j        ]])

### Mesh

In [401]:
def EvenQ(n):
    return(n%2==0)
def OddQ(n):
    return(n%2==1)    

In [402]:
def computeNLayers(evenCount, oddCount, totCount):
    if totCount == 1:
        return 1
    comboCount = evenCount + oddCount
    nComboLayers = totCount//comboCount
    if nComboLayers*comboCount == totCount:
        return 2*nComboLayers
    else:
        return 2*nComboLayers + 1

computeNLayers(evenCount=2, oddCount=1, totCount=6)


4

In [403]:
def generateDeviceLabels(kernelSize, mixerLabel='m', thruLabel='t', verbose=False):
    NN = kernelSize
    evenCount = NN//2
    oddCount = (NN-1)//2
    if verbose: print("NN:", NN)
    nMixers = NN*(NN-1)//2
    if verbose: print("nDOFs:", nMixers)
    if verbose: print("evenCounts:", evenCount, "\toddCounts:", oddCount)
    nLayers = computeNLayers(evenCount, oddCount, nMixers)
    if verbose: print("nLayers:", nLayers)
    mixers = []
    thrus = []
    (i, j) = (0, 0)
    while i < nLayers:
        oddLayer = (i%2 == 1)
        if (j == 0 and oddLayer) or (j == NN - 1):
            thrus.append((thruLabel, i, j))
            j += 1
        else:
            mixers.append((mixerLabel, i, j))
            j += 2
        if j >= NN:
            j = 0
            i += 1
    if verbose: print("mixers:", mixers)
    if verbose: print("thrus:", thrus)
    return (mixers, thrus)

In [404]:
mLabels, tLabels = generateDeviceLabels(kernelSize=5, mixerLabel='m', thruLabel='t', verbose=True)

NN: 5
nDOFs: 10
evenCounts: 2 	oddCounts: 2
nLayers: 5
mixers: [('m', 0, 0), ('m', 0, 2), ('m', 1, 1), ('m', 1, 3), ('m', 2, 0), ('m', 2, 2), ('m', 3, 1), ('m', 3, 3), ('m', 4, 0), ('m', 4, 2)]
thrus: [('t', 0, 4), ('t', 1, 0), ('t', 2, 4), ('t', 3, 0), ('t', 4, 4)]


In [405]:
for NN in range(2,10):
    evenCount = NN//2
    oddCount = (NN-1)//2
    nMixers = NN*(NN-1)//2
    nLayers = computeNLayers(evenCount, oddCount, nMixers)
    print(NN, nLayers)

2 1
3 3
4 4
5 5
6 6
7 7
8 8
9 9


In [406]:
def generateDeviceLabels2(kernelSize, mixerLabel='m', thruLabel='t', verbose=False):
    NN = kernelSize
    orderedLabels = []
    for i in range(NN-1):
        diagList = []
        for j in range(i+1):
            if EvenQ(i):
                label = (mixerLabel, j, i - j)
            else:
                label = (mixerLabel, NN - j - 1, NN - (i - j) - 2)
            diagList.append(label)
        orderedLabels.append(diagList)
    return orderedLabels

In [407]:
generateDeviceLabels2(6, mixerLabel='m', thruLabel='t', verbose=False)

[[('m', 0, 0)],
 [('m', 5, 3), ('m', 4, 4)],
 [('m', 0, 2), ('m', 1, 1), ('m', 2, 0)],
 [('m', 5, 1), ('m', 4, 2), ('m', 3, 3), ('m', 2, 4)],
 [('m', 0, 4), ('m', 1, 3), ('m', 2, 2), ('m', 3, 1), ('m', 4, 0)]]

In [246]:
NN = 5
DOFs = NN*(NN-1)/2
print(DOFs)

10.0


### Sample Problem

In [508]:
U = getRandomUnitaryMatrix(n=2)

In [509]:
mixer1 = Mixer((0.2*pi, 0.3*pi), (0,1))

In [510]:
import sympy as sp

In [511]:
theta, phi = sp.symbols('theta, phi')

In [512]:
# mixer1.theta = theta
# mixer1.phi = phi

In [513]:
from scipy.optimize import minimize

In [516]:
def f(X, matrixProduct, mixer, ):
    mixer1.theta, mixer1.phi = X
    Ttot = U@(mixer1.Tinv(N=2, lines=(0,1)))
    return np.abs(Ttot[0,1])


In [517]:
sol = minimize(f, [0,0])
mixer1.theta, mixer1.phi = sol.x

In [521]:
U@(mixer1.Tinv(N=2, lines=(0,1)))

array([[ 9.74858101e-01-2.22826574e-01j,  9.98716720e-10-4.70063433e-10j],
       [ 8.96188346e-10+6.44391762e-10j, -9.17839387e-01-3.96951962e-01j]])

In [522]:
U

array([[ 0.38314995+0.10215027j,  0.89493962-0.20455934j],
       [ 0.57534654+0.71535851j, -0.36395377-0.15740462j]])

In [524]:
U/(mixer1.T(N=2, lines=(0,1)))

array([[ 0.9748581 -0.22282657j,  0.9748581 -0.22282657j],
       [-0.91783939-0.39695196j, -0.91783938-0.39695196j]])

In [492]:
mixer1.T(N=2)

array([[ 0.10547923-0.07070797j, -0.01067749+0.1210356j ],
       [ 0.8076702 -0.04340566j,  0.49448906-0.68559704j]])